######################################################################
# Automatically generated by qmake (2.01a) sam. sept. 29 23:05:02 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

HEADERS += main_window.h \
  subtitle.h

FORMS += main_window.ui

SOURCES += main.cpp \
  main_window.cpp \
  subtitle.cpp
